In [ ]:
import numpy as np

In [ ]:
arr = np.array([12, 23, 56, 45, 6, 89, 90, 34, 67, 12])
print(np.where(arr % 2 == 0, arr, 0))

[12  0 56  0  6  0 90 34  0 12]


In [12]:
arr = np.array([12, 23, 56, 45, 6, 89, 90, 34, 67, 12])
print(np.where(arr % 2 == 0, arr, 0))
print(np.sum(arr))

[12  0 56  0  6  0 90 34  0 12]
434


In [2]:
import numpy as np
arr = np.array([12, 23, 56, 45, 6, 89, 90, 34, 67, 12])
div3 = arr[arr % 3 == 0]
print(div3)
print(np.mean(div3))

[12 45  6 90 12]
33.0


In [ ]:
arr=np.array([12, 23, 56, 45, 6, 89, 90, 34, 67, 12])