In [ ]:
1-> create a 3d array having 9 elements.
2-> create 2d array having 32 elements.
3-> reshape the above array in two different shapes.
4-> find the transpose of each array

In [1]:
import numpy as np

# 1. Create a 3D array having 9 elements
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])

print("3D Array:")
print(arr3d)
print("Shape:", arr3d.shape)

3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape: (1, 3, 3)


In [2]:

# 2. Create a 2D array having 32 elements
arr2d = np.arange(1, 33).reshape(4, 8)

print("\n2D Array:")
print(arr2d)
print("Shape:", arr2d.shape)



2D Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]
Shape: (4, 8)


In [3]:
# 3. Reshape the above arrays into two different shapes

# 3D array: 9 elements → 3x3 and 1x9
reshape3d_1 = arr3d.reshape(3, 3)
reshape3d_2 = arr3d.reshape(1, 9)

print("\n3D Array - Reshaped to (3,3):")
print(reshape3d_1)

print("\n3D Array - Reshaped to (1,9):")
print(reshape3d_2)


# 2D array: 32 elements → 8x4 and 2x16
reshape2d_1 = arr2d.reshape(8, 4)
reshape2d_2 = arr2d.reshape(2, 16)

print("\n2D Array - Reshaped to (8,4):")
print(reshape2d_1)

print("\n2D Array - Reshaped to (2,16):")
print(reshape2d_2)


3D Array - Reshaped to (3,3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array - Reshaped to (1,9):
[[1 2 3 4 5 6 7 8 9]]

2D Array - Reshaped to (8,4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

2D Array - Reshaped to (2,16):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]]


In [4]:
# 4. Find transpose of each array

print("\nTranspose of 3D Array:")
print(arr3d.T)

print("\nTranspose of 2D Array:")
print(arr2d.T)

print("\nTranspose of 3x3 reshaped array:")
print(reshape3d_1.T)

print("\nTranspose of 4x8 reshaped array:")
print(arr2d.T)


Transpose of 3D Array:
[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]

Transpose of 2D Array:
[[ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]
 [ 8 16 24 32]]

Transpose of 3x3 reshaped array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of 4x8 reshaped array:
[[ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]
 [ 8 16 24 32]]
