In [1]:
import numpy as np 

In [6]:
demo= np.array([[1,2,4,7,79,987,76,8755,4,3,2,1]])
demo.shape
demo.reshape(2,2,3)


array([[[   1,    2,    4],
        [   7,   79,  987]],

       [[  76, 8755,    4],
        [   3,    2,    1]]])

In [ ]:
res= np.array([[[1,2,4],[7,79,987]],[[76,8755,4],[3,2,1]]])
print(res%10)


[[[1 2 4]
  [7 9 7]]

 [[6 5 4]
  [3 2 1]]]


In [ ]:
demo= np.array([[100,2222,8755]])
print(demo%10)


[[0 2 5]]


In [18]:
k=np.array([100,56,87,56,65,78,89,76,45,57,87])
mask = k>70
print(k)

[100  56  87  56  65  78  89  76  45  57  87]


In [9]:
k=np.array([100,56,87,56,65,78,89,76,45,57,87])
mask = (k>70) & (k<90)
print(k[mask])
print(k[~mask])

[87 78 89 76 87]
[100  56  56  65  45  57]


In [10]:
cond=[(k>=50) & (k<=80), (k>=80) & (k<=100)]
choice=["Small","Large"]
np.select(cond,choice,default="Big")

array(['Large', 'Small', 'Large', 'Small', 'Small', 'Small', 'Large',
       'Small', 'Big', 'Small', 'Large'], dtype='<U5')